### ISSUE TITLE
lcmark is not support lujit ?

### ISSUE THREAD

**Issue by ghost** [jgm/lcmark#3]
luarocks install lcmark

Error: lcmark supports only Lua 5.2 and Lua 5.3 but not Lua 5.1.

Why is luajit not supported?

(I am using 2.1.0-beta 3 of Luajit )

**Comment by jgm** [comment]
> Why is luajit not supported?

We require lua 5.2 because we're using some features that
are only present in 5.2.

If luajit now supports the lua 5.2 API, then it should
work.  (Last I checked, it didn't, but that was a long
time ago.)

Feel free to try it!  The rockspec currently specifies
lua >= 5.2. I don't know if there's any way to say that
lua >= 5.2 or luajit >= ?? will work?

**Comment by jgm** [comment]
Fixed by #4

**Comment by kasbah** [comment]
I guess this wasn't released on luarocks though? As lua noob it took me quite a while to figure out why luarocks says `lcmark` doesn't exist. All I was trying to do was compile the commonmark spec and I just followed the instructions for that on Ubuntu 16.04.
